name: code_check
description: Perform MeshPy code checks
runs:
  using: composite
  steps:
    - name: Code Checks
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        source python-testing-environment/bin/activate
        pip install -e .[CI-CD]
        pre-commit install --install-hooks
        SKIP=no-commit-to-branch pre-commit run --all-files
        exit 1
