name: Check MeshPy to BeamMe redirects

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub repo redirect
        run: |
          final_url=$(curl -sL -o /dev/null -w "%{url_effective}" "https://github.com/imcs-compsim/meshpy/")
          echo "Repo redirect: $final_url"
          [ "$final_url" = "https://github.com/beamme-py/beamme" ] || {
            echo "Repo redirect failed"
            exit 1
          }

      - name: Check GitHub Pages meta redirect
        run: |
          redirect_url=$(curl -s "https://imcs-compsim.github.io/meshpy/" | grep -i 'http-equiv="refresh"' | sed -E 's/.*content="[0-9]+;\s*URL=([^"]*)".*/\1/I')
          echo "Pages redirect: $redirect_url"
          [ "$redirect_url" = "https://beamme-py.github.io/beamme/" ] || {
            echo "Pages redirect failed"
            exit 1
          }
