
name: Test MeshPy during pull requests

on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    type: choice

jobs:

  meshpy-testing:
    name: Run MeshPy test suite
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup virtual python environment
        uses: ./.github/actions/setup_virtual_python_environment
      - name: Run the test suite
        uses: ./.github/actions/run_tests
        with:
          require_cubitpy: 0
          require_four_c: 0
          require_arborx: 0
      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.job}}-${{github.run_number}}
          path: ${{github.workspace}}/tests/testing-tmp/